// <auto-generated />
using System;
using MasoloAgro.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasoloAgro.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925091301_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Commodity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReorderLevelKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Commodities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Commodities_CurrentPrice", "CAST(CurrentPrice AS REAL) >= 0");

                            t.HasCheckConstraint("CK_Commodities_ReorderLevelKg", "CAST(ReorderLevelKg AS REAL) >= 0");

                            t.HasCheckConstraint("CK_Commodities_StockKg", "CAST(StockKg AS REAL) >= 0");
                        });
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceivedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("SaleId");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "CAST(Amount AS REAL) > 0");

                            t.HasCheckConstraint("CK_Payments_OneParent", "(SaleId IS NOT NULL AND PurchaseId IS NULL) OR (SaleId IS NULL AND PurchaseId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BalanceDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReversedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RefNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Purchases", null, t =>
                        {
                            t.HasCheckConstraint("CK_Purchases_AmountPaid", "CAST(AmountPaid AS REAL) >= 0 AND CAST(AmountPaid AS REAL) <= CAST(Total AS REAL)");

                            t.HasCheckConstraint("CK_Purchases_BalanceDue", "CAST(BalanceDue AS REAL) >= 0");

                            t.HasCheckConstraint("CK_Purchases_Total", "CAST(Total AS REAL) >= 0");
                        });
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.PurchaseLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseLines_LineTotal", "CAST(LineTotal AS REAL) >= 0");

                            t.HasCheckConstraint("CK_PurchaseLines_QuantityKg", "CAST(QuantityKg AS REAL) > 0");

                            t.HasCheckConstraint("CK_PurchaseLines_UnitPrice", "CAST(UnitPrice AS REAL) >= 0");
                        });
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BalanceDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReversedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RefNumber")
                        .IsUnique();

                    b.ToTable("Sales", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sales_AmountPaid", "CAST(AmountPaid AS REAL) >= 0 AND CAST(AmountPaid AS REAL) <= CAST(Total AS REAL)");

                            t.HasCheckConstraint("CK_Sales_BalanceDue", "CAST(BalanceDue AS REAL) >= 0");

                            t.HasCheckConstraint("CK_Sales_Total", "CAST(Total AS REAL) >= 0");
                        });
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_SaleLines_LineTotal", "CAST(LineTotal AS REAL) >= 0");

                            t.HasCheckConstraint("CK_SaleLines_QuantityKg", "CAST(QuantityKg AS REAL) > 0");

                            t.HasCheckConstraint("CK_SaleLines_UnitPrice", "CAST(UnitPrice AS REAL) >= 0");
                        });
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityChangeKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("StockAdjustments", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockAdjustments_Change", "CAST(QuantityChangeKg AS REAL) <> 0");
                        });
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovementType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StockAdjustmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommodityId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MovementDate");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("SaleId");

                    b.HasIndex("StockAdjustmentId");

                    b.ToTable("StockMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockMovements_OneSource", "(CASE WHEN SaleId IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN PurchaseId IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN StockAdjustmentId IS NOT NULL THEN 1 ELSE 0 END) <= 1");

                            t.HasCheckConstraint("CK_StockMovements_QuantityKg", "CAST(QuantityKg AS REAL) > 0");
                        });
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MasoloAgro.Domain.Entities.Purchase", "Purchase")
                        .WithMany("Payments")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MasoloAgro.Domain.Entities.User", "ReceivedBy")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MasoloAgro.Domain.Entities.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Purchase");

                    b.Navigation("ReceivedBy");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("MasoloAgro.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MasoloAgro.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.PurchaseLine", b =>
                {
                    b.HasOne("MasoloAgro.Domain.Entities.Commodity", "Commodity")
                        .WithMany("PurchaseLines")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MasoloAgro.Domain.Entities.Purchase", "Purchase")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Sale", b =>
                {
                    b.HasOne("MasoloAgro.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MasoloAgro.Domain.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.SaleLine", b =>
                {
                    b.HasOne("MasoloAgro.Domain.Entities.Commodity", "Commodity")
                        .WithMany("SaleLines")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MasoloAgro.Domain.Entities.Sale", "Sale")
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.StockAdjustment", b =>
                {
                    b.HasOne("MasoloAgro.Domain.Entities.Commodity", "Commodity")
                        .WithMany("Adjustments")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MasoloAgro.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Commodity");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("MasoloAgro.Domain.Entities.Commodity", "Commodity")
                        .WithMany("Movements")
                        .HasForeignKey("CommodityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MasoloAgro.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MasoloAgro.Domain.Entities.Purchase", "Purchase")
                        .WithMany("Movements")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MasoloAgro.Domain.Entities.Sale", "Sale")
                        .WithMany("Movements")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MasoloAgro.Domain.Entities.StockAdjustment", "StockAdjustment")
                        .WithMany("Movements")
                        .HasForeignKey("StockAdjustmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Commodity");

                    b.Navigation("CreatedBy");

                    b.Navigation("Purchase");

                    b.Navigation("Sale");

                    b.Navigation("StockAdjustment");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("MasoloAgro.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Commodity", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Movements");

                    b.Navigation("PurchaseLines");

                    b.Navigation("SaleLines");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Movements");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Movements");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.StockAdjustment", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("MasoloAgro.Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
